/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jboss_rhiot_ble_bluez_HCIDump */

#ifndef _Included_org_jboss_rhiot_ble_bluez_HCIDump
#define _Included_org_jboss_rhiot_ble_bluez_HCIDump
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jboss_rhiot_ble_bluez_HCIDump_beacon_info_SIZEOF
#define org_jboss_rhiot_ble_bluez_HCIDump_beacon_info_SIZEOF 80L
#undef org_jboss_rhiot_ble_bluez_HCIDump_UUID_OFFSET
#define org_jboss_rhiot_ble_bluez_HCIDump_UUID_OFFSET 0L
#undef org_jboss_rhiot_ble_bluez_HCIDump_IS_HEARTBEAT_OFFSET
#define org_jboss_rhiot_ble_bluez_HCIDump_IS_HEARTBEAT_OFFSET 36L
#undef org_jboss_rhiot_ble_bluez_HCIDump_count_OFFSET
#define org_jboss_rhiot_ble_bluez_HCIDump_count_OFFSET 40L
#undef org_jboss_rhiot_ble_bluez_HCIDump_code_OFFSET
#define org_jboss_rhiot_ble_bluez_HCIDump_code_OFFSET 44L
#undef org_jboss_rhiot_ble_bluez_HCIDump_manufacturer_OFFSET
#define org_jboss_rhiot_ble_bluez_HCIDump_manufacturer_OFFSET 48L
#undef org_jboss_rhiot_ble_bluez_HCIDump_major_OFFSET
#define org_jboss_rhiot_ble_bluez_HCIDump_major_OFFSET 52L
#undef org_jboss_rhiot_ble_bluez_HCIDump_minor_OFFSET
#define org_jboss_rhiot_ble_bluez_HCIDump_minor_OFFSET 56L
#undef org_jboss_rhiot_ble_bluez_HCIDump_power_OFFSET
#define org_jboss_rhiot_ble_bluez_HCIDump_power_OFFSET 60L
#undef org_jboss_rhiot_ble_bluez_HCIDump_calibrated_power_OFFSET
#define org_jboss_rhiot_ble_bluez_HCIDump_calibrated_power_OFFSET 64L
#undef org_jboss_rhiot_ble_bluez_HCIDump_rssi_OFFSET
#define org_jboss_rhiot_ble_bluez_HCIDump_rssi_OFFSET 68L
#undef org_jboss_rhiot_ble_bluez_HCIDump_time_OFFSET
#define org_jboss_rhiot_ble_bluez_HCIDump_time_OFFSET 72L
#undef org_jboss_rhiot_ble_bluez_HCIDump_ADI_total_length_OFFSET
#define org_jboss_rhiot_ble_bluez_HCIDump_ADI_total_length_OFFSET 0L
#undef org_jboss_rhiot_ble_bluez_HCIDump_ADI_bdaddr_type_OFFSET
#define org_jboss_rhiot_ble_bluez_HCIDump_ADI_bdaddr_type_OFFSET 4L
#undef org_jboss_rhiot_ble_bluez_HCIDump_ADI_bdaddr_OFFSET
#define org_jboss_rhiot_ble_bluez_HCIDump_ADI_bdaddr_OFFSET 5L
#undef org_jboss_rhiot_ble_bluez_HCIDump_ADI_count_OFFSET
#define org_jboss_rhiot_ble_bluez_HCIDump_ADI_count_OFFSET 11L
#undef org_jboss_rhiot_ble_bluez_HCIDump_ADI_rssi_OFFSET
#define org_jboss_rhiot_ble_bluez_HCIDump_ADI_rssi_OFFSET 12L
#undef org_jboss_rhiot_ble_bluez_HCIDump_ADI_time_OFFSET
#define org_jboss_rhiot_ble_bluez_HCIDump_ADI_time_OFFSET 16L
#undef org_jboss_rhiot_ble_bluez_HCIDump_ADI_data_OFFSET
#define org_jboss_rhiot_ble_bluez_HCIDump_ADI_data_OFFSET 24L
/*
 * Class:     org_jboss_rhiot_ble_bluez_HCIDump
 * Method:    allocScanner
 * Signature: (Ljava/nio/ByteBuffer;IZ)V
 */
JNIEXPORT void JNICALL Java_org_jboss_rhiot_ble_bluez_HCIDump_allocScanner
        (JNIEnv *, jclass, jobject, jint, jboolean);

/*
 * Class:     org_jboss_rhiot_ble_bluez_HCIDump
 * Method:    freeScanner
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jboss_rhiot_ble_bluez_HCIDump_freeScanner
        (JNIEnv *, jclass);

/*
 * Class:     org_jboss_rhiot_ble_bluez_HCIDump
 * Method:    enableDebugMode
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_jboss_rhiot_ble_bluez_HCIDump_enableDebugMode
        (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
